DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS component;
DROP TABLE IF EXISTS stock;
DROP TABLE IF EXISTS stock_component;
DROP TABLE IF EXISTS sample;
DROP TABLE IF EXISTS sample_stock;
DROP TABLE IF EXISTS measurement;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE component (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    mass REAL NOT NULL,
    mass_units TEXT NOT NULL DEFAULT 'mg',
    density REAL NOT NULL,
    density_units TEXT NOT NULL DEFAULT 'g/ml',
    formula TEXT NOT NULL,
    sld REAL
);

CREATE TABLE stock (
    id INTEGER UNIQUE NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL
);

CREATE TABLE stock_component (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    component_id INTEGER NOT NULL,
    stock_id INTEGER NOT NULL,
    amount INTEGER NOT NULL,
    units TEXT NOT NULL,
    volmass TEXT NOT NULL,
    FOREIGN KEY (component_id) REFERENCES component (id),
    FOREIGN KEY (stock_id) REFERENCES stock (id)
);

CREATE TABLE sample (
    id INTEGER UNIQUE NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL
);

CREATE TABLE sample_stock (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sample_id INTEGER NOT NULL,
    stock_id INTEGER NOT NULL,
    amount REAL NOT NULL,
    units TEXT NOT NULL,
    volmass TEXT NOT NULL,
    FOREIGN KEY (sample_id) REFERENCES sample (id),
    FOREIGN KEY (stock_id) REFERENCES stock (id)
);

CREATE TABLE measurement (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sample_id INTEGER NOT NULL,
    metadata BLOB NOT NULL,
    FOREIGN KEY (sample_id) REFERENCES sample (id)
);