authentication:
  # The default is false. Set to true to enable any HTTP client that can
  # connect to _read_. An API key is still required to write.
  single_user_api_key: "" # generate using `openssl rand -hex 32`
uvicorn:
  host: "0.0.0.0"
  port: 8000
trees:
  - path: /
    tree: catalog
    args:
      uri: "sqlite+aiosqlite:///catalog.db"
      writable_storage: "data/"
      # This creates the database if it does not exist. This is convenient, but in
      # a horizonally-scaled deployment, this can be a race condition and multiple
      # containers may simultanouesly attempt to create the database.
      # If that is a problem, set this to false, and run:
      #
      # tiled catalog init URI
      #
      # separately.
      init_if_not_exists: true
